services:
  - type: web
    name: fastapi-investments
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app.main:app --workers 1 --worker-class uvicorn.workers.UvicornWorker"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
